<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kinematics" nsURI="https://de/fraunhofer/ipa/kinematics" nsPrefix="de.fraunhofer.ipa.kinematics">
  <eClassifiers xsi:type="ecore:EClass" name="robot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="root_link" lowerBound="1"
        eType="#//link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joint" upperBound="-1"
        eType="#//joint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="link">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="joint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" lowerBound="1" upperBound="-1"
        eType="#//link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
