/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.kinematics.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import de.fraunhofer.ipa.kinematics.ide.contentassist.antlr.internal.InternalKinematicsParser;
import de.fraunhofer.ipa.kinematics.services.KinematicsGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class KinematicsParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(KinematicsGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, KinematicsGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getRobotAccess().getGroup(), "rule__Robot__Group__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getJointAccess().getGroup(), "rule__Joint__Group__0");
			builder.put(grammarAccess.getJointAccess().getGroup_10(), "rule__Joint__Group_10__0");
			builder.put(grammarAccess.getJointAccess().getGroup_11(), "rule__Joint__Group_11__0");
			builder.put(grammarAccess.getJointAccess().getGroup_12(), "rule__Joint__Group_12__0");
			builder.put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_4(), "rule__Link__Group_4__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_5(), "rule__Link__Group_5__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_6(), "rule__Link__Group_6__0");
			builder.put(grammarAccess.getAxisAccess().getGroup(), "rule__Axis__Group__0");
			builder.put(grammarAccess.getAxisAccess().getGroup_3(), "rule__Axis__Group_3__0");
			builder.put(grammarAccess.getPoseAccess().getGroup(), "rule__Pose__Group__0");
			builder.put(grammarAccess.getPoseAccess().getGroup_3(), "rule__Pose__Group_3__0");
			builder.put(grammarAccess.getPoseAccess().getGroup_4(), "rule__Pose__Group_4__0");
			builder.put(grammarAccess.getLimitAccess().getGroup(), "rule__Limit__Group__0");
			builder.put(grammarAccess.getLimitAccess().getGroup_3(), "rule__Limit__Group_3__0");
			builder.put(grammarAccess.getLimitAccess().getGroup_4(), "rule__Limit__Group_4__0");
			builder.put(grammarAccess.getLimitAccess().getGroup_5(), "rule__Limit__Group_5__0");
			builder.put(grammarAccess.getLimitAccess().getGroup_6(), "rule__Limit__Group_6__0");
			builder.put(grammarAccess.getInertialAccess().getGroup(), "rule__Inertial__Group__0");
			builder.put(grammarAccess.getInertialAccess().getGroup_3(), "rule__Inertial__Group_3__0");
			builder.put(grammarAccess.getInertialAccess().getGroup_4(), "rule__Inertial__Group_4__0");
			builder.put(grammarAccess.getInertialAccess().getGroup_5(), "rule__Inertial__Group_5__0");
			builder.put(grammarAccess.getVisualAccess().getGroup(), "rule__Visual__Group__0");
			builder.put(grammarAccess.getVisualAccess().getGroup_2(), "rule__Visual__Group_2__0");
			builder.put(grammarAccess.getCollisionAccess().getGroup(), "rule__Collision__Group__0");
			builder.put(grammarAccess.getCollisionAccess().getGroup_2(), "rule__Collision__Group_2__0");
			builder.put(grammarAccess.getMassAccess().getGroup(), "rule__Mass__Group__0");
			builder.put(grammarAccess.getMassAccess().getGroup_3(), "rule__Mass__Group_3__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup(), "rule__Inertia__Group__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup_3(), "rule__Inertia__Group_3__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup_4(), "rule__Inertia__Group_4__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup_5(), "rule__Inertia__Group_5__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup_6(), "rule__Inertia__Group_6__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup_7(), "rule__Inertia__Group_7__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup_8(), "rule__Inertia__Group_8__0");
			builder.put(grammarAccess.getGeometryAccess().getGroup(), "rule__Geometry__Group__0");
			builder.put(grammarAccess.getGeometryAccess().getGroup_3(), "rule__Geometry__Group_3__0");
			builder.put(grammarAccess.getGeometryAccess().getGroup_4(), "rule__Geometry__Group_4__0");
			builder.put(grammarAccess.getGeometryAccess().getGroup_5(), "rule__Geometry__Group_5__0");
			builder.put(grammarAccess.getGeometryAccess().getGroup_6(), "rule__Geometry__Group_6__0");
			builder.put(grammarAccess.getBoxAccess().getGroup(), "rule__Box__Group__0");
			builder.put(grammarAccess.getBoxAccess().getGroup_3(), "rule__Box__Group_3__0");
			builder.put(grammarAccess.getCylinderAccess().getGroup(), "rule__Cylinder__Group__0");
			builder.put(grammarAccess.getSphereAccess().getGroup(), "rule__Sphere__Group__0");
			builder.put(grammarAccess.getMeshAccess().getGroup(), "rule__Mesh__Group__0");
			builder.put(grammarAccess.getMeshAccess().getGroup_4(), "rule__Mesh__Group_4__0");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_2(), "rule__Parameter__NameAssignment_2");
			builder.put(grammarAccess.getJointAccess().getNameAssignment_3(), "rule__Joint__NameAssignment_3");
			builder.put(grammarAccess.getJointAccess().getTypeAssignment_5(), "rule__Joint__TypeAssignment_5");
			builder.put(grammarAccess.getJointAccess().getParentAssignment_7(), "rule__Joint__ParentAssignment_7");
			builder.put(grammarAccess.getJointAccess().getChildAssignment_9(), "rule__Joint__ChildAssignment_9");
			builder.put(grammarAccess.getJointAccess().getOriginAssignment_10_1(), "rule__Joint__OriginAssignment_10_1");
			builder.put(grammarAccess.getJointAccess().getAxisAssignment_11_1(), "rule__Joint__AxisAssignment_11_1");
			builder.put(grammarAccess.getJointAccess().getLimitAssignment_12_1(), "rule__Joint__LimitAssignment_12_1");
			builder.put(grammarAccess.getLinkAccess().getNameAssignment_3(), "rule__Link__NameAssignment_3");
			builder.put(grammarAccess.getLinkAccess().getInertialAssignment_4_1(), "rule__Link__InertialAssignment_4_1");
			builder.put(grammarAccess.getLinkAccess().getVisualAssignment_5_1(), "rule__Link__VisualAssignment_5_1");
			builder.put(grammarAccess.getLinkAccess().getCollisionAssignment_6_1(), "rule__Link__CollisionAssignment_6_1");
			builder.put(grammarAccess.getAxisAccess().getXyzAssignment_3_1(), "rule__Axis__XyzAssignment_3_1");
			builder.put(grammarAccess.getPoseAccess().getRpyAssignment_3_1(), "rule__Pose__RpyAssignment_3_1");
			builder.put(grammarAccess.getPoseAccess().getXyzAssignment_4_1(), "rule__Pose__XyzAssignment_4_1");
			builder.put(grammarAccess.getLimitAccess().getEffortAssignment_3_1(), "rule__Limit__EffortAssignment_3_1");
			builder.put(grammarAccess.getLimitAccess().getLowerAssignment_4_1(), "rule__Limit__LowerAssignment_4_1");
			builder.put(grammarAccess.getLimitAccess().getUpperAssignment_5_1(), "rule__Limit__UpperAssignment_5_1");
			builder.put(grammarAccess.getLimitAccess().getVelocityAssignment_6_1(), "rule__Limit__VelocityAssignment_6_1");
			builder.put(grammarAccess.getInertialAccess().getOriginAssignment_3_1(), "rule__Inertial__OriginAssignment_3_1");
			builder.put(grammarAccess.getInertialAccess().getMassAssignment_4_1(), "rule__Inertial__MassAssignment_4_1");
			builder.put(grammarAccess.getInertialAccess().getInertiaAssignment_5_1(), "rule__Inertial__InertiaAssignment_5_1");
			builder.put(grammarAccess.getVisualAccess().getOriginAssignment_2_1(), "rule__Visual__OriginAssignment_2_1");
			builder.put(grammarAccess.getVisualAccess().getGeometryAssignment_4(), "rule__Visual__GeometryAssignment_4");
			builder.put(grammarAccess.getCollisionAccess().getOriginAssignment_2_1(), "rule__Collision__OriginAssignment_2_1");
			builder.put(grammarAccess.getCollisionAccess().getGeometryAssignment_4(), "rule__Collision__GeometryAssignment_4");
			builder.put(grammarAccess.getMassAccess().getValueAssignment_3_1(), "rule__Mass__ValueAssignment_3_1");
			builder.put(grammarAccess.getInertiaAccess().getIxxAssignment_3_1(), "rule__Inertia__IxxAssignment_3_1");
			builder.put(grammarAccess.getInertiaAccess().getIxyAssignment_4_1(), "rule__Inertia__IxyAssignment_4_1");
			builder.put(grammarAccess.getInertiaAccess().getIxzAssignment_5_1(), "rule__Inertia__IxzAssignment_5_1");
			builder.put(grammarAccess.getInertiaAccess().getIyyAssignment_6_1(), "rule__Inertia__IyyAssignment_6_1");
			builder.put(grammarAccess.getInertiaAccess().getIyzAssignment_7_1(), "rule__Inertia__IyzAssignment_7_1");
			builder.put(grammarAccess.getInertiaAccess().getIzzAssignment_8_1(), "rule__Inertia__IzzAssignment_8_1");
			builder.put(grammarAccess.getGeometryAccess().getBoxAssignment_3_1(), "rule__Geometry__BoxAssignment_3_1");
			builder.put(grammarAccess.getGeometryAccess().getCylinderAssignment_4_1(), "rule__Geometry__CylinderAssignment_4_1");
			builder.put(grammarAccess.getGeometryAccess().getSphereAssignment_5_1(), "rule__Geometry__SphereAssignment_5_1");
			builder.put(grammarAccess.getGeometryAccess().getMeshAssignment_6_1(), "rule__Geometry__MeshAssignment_6_1");
			builder.put(grammarAccess.getBoxAccess().getSizeAssignment_3_1(), "rule__Box__SizeAssignment_3_1");
			builder.put(grammarAccess.getCylinderAccess().getLengthAssignment_3(), "rule__Cylinder__LengthAssignment_3");
			builder.put(grammarAccess.getCylinderAccess().getRadiusAssignment_5(), "rule__Cylinder__RadiusAssignment_5");
			builder.put(grammarAccess.getSphereAccess().getRadiusAssignment_3(), "rule__Sphere__RadiusAssignment_3");
			builder.put(grammarAccess.getMeshAccess().getFilenameAssignment_3(), "rule__Mesh__FilenameAssignment_3");
			builder.put(grammarAccess.getMeshAccess().getScaleAssignment_4_1(), "rule__Mesh__ScaleAssignment_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private KinematicsGrammarAccess grammarAccess;

	@Override
	protected InternalKinematicsParser createParser() {
		InternalKinematicsParser result = new InternalKinematicsParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public KinematicsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KinematicsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
