/*
 * generated by Xtext 2.25.0
 */
package de.fraunhofer.ipa.kinematics.xacro.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class XacroUiModule extends AbstractXacroUiModule {

	public XacroUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
