/*
 * generated by Xtext 2.25.0
 */
package de.fraunhofer.ipa.kinematics.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import de.fraunhofer.ipa.kinematics.ide.contentassist.antlr.internal.InternalKinematicsParser;
import de.fraunhofer.ipa.kinematics.services.KinematicsGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class KinematicsParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(KinematicsGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, KinematicsGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getRobotAccess().getGroup(), "rule__Robot__Group__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_4(), "rule__Robot__Group_4__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_4_3(), "rule__Robot__Group_4_3__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_5(), "rule__Robot__Group_5__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_6(), "rule__Robot__Group_6__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_7(), "rule__Robot__Group_7__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_7_3(), "rule__Robot__Group_7_3__0");
			builder.put(grammarAccess.getRef_robotAccess().getGroup(), "rule__Ref_robot__Group__0");
			builder.put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
			builder.put(grammarAccess.getJointAccess().getGroup(), "rule__Joint__Group__0");
			builder.put(grammarAccess.getRobotAccess().getNameAssignment_2(), "rule__Robot__NameAssignment_2");
			builder.put(grammarAccess.getRobotAccess().getRobotsAssignment_4_2(), "rule__Robot__RobotsAssignment_4_2");
			builder.put(grammarAccess.getRobotAccess().getRobotsAssignment_4_3_1(), "rule__Robot__RobotsAssignment_4_3_1");
			builder.put(grammarAccess.getRobotAccess().getPrefixAssignment_5_1(), "rule__Robot__PrefixAssignment_5_1");
			builder.put(grammarAccess.getRobotAccess().getRoot_linkAssignment_6_1(), "rule__Robot__Root_linkAssignment_6_1");
			builder.put(grammarAccess.getRobotAccess().getJointsAssignment_7_2(), "rule__Robot__JointsAssignment_7_2");
			builder.put(grammarAccess.getRobotAccess().getJointsAssignment_7_3_1(), "rule__Robot__JointsAssignment_7_3_1");
			builder.put(grammarAccess.getRef_robotAccess().getRobotAssignment_2(), "rule__Ref_robot__RobotAssignment_2");
			builder.put(grammarAccess.getRef_robotAccess().getPrefixAssignment_4(), "rule__Ref_robot__PrefixAssignment_4");
			builder.put(grammarAccess.getLinkAccess().getNameAssignment_2(), "rule__Link__NameAssignment_2");
			builder.put(grammarAccess.getJointAccess().getNameAssignment_1(), "rule__Joint__NameAssignment_1");
			builder.put(grammarAccess.getJointAccess().getParentAssignment_4(), "rule__Joint__ParentAssignment_4");
			builder.put(grammarAccess.getJointAccess().getChildAssignment_6(), "rule__Joint__ChildAssignment_6");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private KinematicsGrammarAccess grammarAccess;

	@Override
	protected InternalKinematicsParser createParser() {
		InternalKinematicsParser result = new InternalKinematicsParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public KinematicsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KinematicsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
