/*
 * generated by Xtext 2.25.0
 */
package de.fraunhofer.ipa.kinematics.xacro;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class XacroStandaloneSetup extends XacroStandaloneSetupGenerated {

	public static void doSetup() {
		new XacroStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
