/*
 * generated by Xtext 2.25.0
 */
package de.fraunhofer.ipa.kinematics.xacro.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import de.fraunhofer.ipa.kinematics.xacro.ide.contentassist.antlr.internal.InternalXacroParser;
import de.fraunhofer.ipa.kinematics.xacro.services.XacroGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class XacroParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(XacroGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, XacroGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getParameterValueAccess().getAlternatives(), "rule__ParameterValue__Alternatives");
			builder.put(grammarAccess.getParameterPoseAccess().getAlternatives(), "rule__ParameterPose__Alternatives");
			builder.put(grammarAccess.getParameterLinkAccess().getAlternatives(), "rule__ParameterLink__Alternatives");
			builder.put(grammarAccess.getParameterTypeAccess().getAlternatives(), "rule__ParameterType__Alternatives");
			builder.put(grammarAccess.getRobotAccess().getGroup(), "rule__Robot__Group__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_5(), "rule__Robot__Group_5__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_6(), "rule__Robot__Group_6__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_6_3(), "rule__Robot__Group_6_3__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_7(), "rule__Robot__Group_7__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_7_3(), "rule__Robot__Group_7_3__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_8(), "rule__Robot__Group_8__0");
			builder.put(grammarAccess.getMacroAccess().getGroup(), "rule__Macro__Group__0");
			builder.put(grammarAccess.getMacroAccess().getGroup_4(), "rule__Macro__Group_4__0");
			builder.put(grammarAccess.getMacroAccess().getGroup_4_3(), "rule__Macro__Group_4_3__0");
			builder.put(grammarAccess.getMacroAccess().getGroup_5(), "rule__Macro__Group_5__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getParameterAccess().getGroup_6(), "rule__Parameter__Group_6__0");
			builder.put(grammarAccess.getParameterStringAccess().getGroup(), "rule__ParameterString__Group__0");
			builder.put(grammarAccess.getParameterStringTypeAccess().getGroup(), "rule__ParameterStringType__Group__0");
			builder.put(grammarAccess.getParameterLinkRefTypeAccess().getGroup(), "rule__ParameterLinkRefType__Group__0");
			builder.put(grammarAccess.getParameterPoseTypeAccess().getGroup(), "rule__ParameterPoseType__Group__0");
			builder.put(grammarAccess.getBodyAccess().getGroup(), "rule__Body__Group__0");
			builder.put(grammarAccess.getBodyAccess().getGroup_3(), "rule__Body__Group_3__0");
			builder.put(grammarAccess.getBodyAccess().getGroup_3_3(), "rule__Body__Group_3_3__0");
			builder.put(grammarAccess.getBodyAccess().getGroup_4(), "rule__Body__Group_4__0");
			builder.put(grammarAccess.getBodyAccess().getGroup_4_3(), "rule__Body__Group_4_3__0");
			builder.put(grammarAccess.getMacroCallAccess().getGroup(), "rule__MacroCall__Group__0");
			builder.put(grammarAccess.getMacroCallAccess().getGroup_5(), "rule__MacroCall__Group_5__0");
			builder.put(grammarAccess.getMacroCallAccess().getGroup_5_3(), "rule__MacroCall__Group_5_3__0");
			builder.put(grammarAccess.getParameterCallAccess().getGroup(), "rule__ParameterCall__Group__0");
			builder.put(grammarAccess.getJointAccess().getGroup(), "rule__Joint__Group__0");
			builder.put(grammarAccess.getJointAccess().getGroup_10(), "rule__Joint__Group_10__0");
			builder.put(grammarAccess.getJointAccess().getGroup_11(), "rule__Joint__Group_11__0");
			builder.put(grammarAccess.getJointAccess().getGroup_12(), "rule__Joint__Group_12__0");
			builder.put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_4(), "rule__Link__Group_4__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_5(), "rule__Link__Group_5__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_6(), "rule__Link__Group_6__0");
			builder.put(grammarAccess.getPoseAccess().getGroup(), "rule__Pose__Group__0");
			builder.put(grammarAccess.getPoseAccess().getGroup_3(), "rule__Pose__Group_3__0");
			builder.put(grammarAccess.getPoseAccess().getGroup_4(), "rule__Pose__Group_4__0");
			builder.put(grammarAccess.getVector3Access().getGroup(), "rule__Vector3__Group__0");
			builder.put(grammarAccess.getVector3Access().getGroup_3(), "rule__Vector3__Group_3__0");
			builder.put(grammarAccess.getLimitAccess().getGroup(), "rule__Limit__Group__0");
			builder.put(grammarAccess.getLimitAccess().getGroup_3(), "rule__Limit__Group_3__0");
			builder.put(grammarAccess.getLimitAccess().getGroup_4(), "rule__Limit__Group_4__0");
			builder.put(grammarAccess.getLimitAccess().getGroup_5(), "rule__Limit__Group_5__0");
			builder.put(grammarAccess.getLimitAccess().getGroup_6(), "rule__Limit__Group_6__0");
			builder.put(grammarAccess.getInertialAccess().getGroup(), "rule__Inertial__Group__0");
			builder.put(grammarAccess.getInertialAccess().getGroup_3(), "rule__Inertial__Group_3__0");
			builder.put(grammarAccess.getInertialAccess().getGroup_4(), "rule__Inertial__Group_4__0");
			builder.put(grammarAccess.getInertialAccess().getGroup_5(), "rule__Inertial__Group_5__0");
			builder.put(grammarAccess.getVisualAccess().getGroup(), "rule__Visual__Group__0");
			builder.put(grammarAccess.getVisualAccess().getGroup_2(), "rule__Visual__Group_2__0");
			builder.put(grammarAccess.getCollisionAccess().getGroup(), "rule__Collision__Group__0");
			builder.put(grammarAccess.getCollisionAccess().getGroup_2(), "rule__Collision__Group_2__0");
			builder.put(grammarAccess.getMassAccess().getGroup(), "rule__Mass__Group__0");
			builder.put(grammarAccess.getMassAccess().getGroup_3(), "rule__Mass__Group_3__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup(), "rule__Inertia__Group__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup_3(), "rule__Inertia__Group_3__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup_4(), "rule__Inertia__Group_4__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup_5(), "rule__Inertia__Group_5__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup_6(), "rule__Inertia__Group_6__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup_7(), "rule__Inertia__Group_7__0");
			builder.put(grammarAccess.getInertiaAccess().getGroup_8(), "rule__Inertia__Group_8__0");
			builder.put(grammarAccess.getGeometryAccess().getGroup(), "rule__Geometry__Group__0");
			builder.put(grammarAccess.getGeometryAccess().getGroup_3(), "rule__Geometry__Group_3__0");
			builder.put(grammarAccess.getGeometryAccess().getGroup_4(), "rule__Geometry__Group_4__0");
			builder.put(grammarAccess.getGeometryAccess().getGroup_5(), "rule__Geometry__Group_5__0");
			builder.put(grammarAccess.getGeometryAccess().getGroup_6(), "rule__Geometry__Group_6__0");
			builder.put(grammarAccess.getBoxAccess().getGroup(), "rule__Box__Group__0");
			builder.put(grammarAccess.getBoxAccess().getGroup_3(), "rule__Box__Group_3__0");
			builder.put(grammarAccess.getCylinderAccess().getGroup(), "rule__Cylinder__Group__0");
			builder.put(grammarAccess.getSphereAccess().getGroup(), "rule__Sphere__Group__0");
			builder.put(grammarAccess.getMeshAccess().getGroup(), "rule__Mesh__Group__0");
			builder.put(grammarAccess.getMeshAccess().getGroup_4(), "rule__Mesh__Group_4__0");
			builder.put(grammarAccess.getRobotAccess().getNameAssignment_4(), "rule__Robot__NameAssignment_4");
			builder.put(grammarAccess.getRobotAccess().getVersionAssignment_5_1(), "rule__Robot__VersionAssignment_5_1");
			builder.put(grammarAccess.getRobotAccess().getMacroAssignment_6_2(), "rule__Robot__MacroAssignment_6_2");
			builder.put(grammarAccess.getRobotAccess().getMacroAssignment_6_3_1(), "rule__Robot__MacroAssignment_6_3_1");
			builder.put(grammarAccess.getRobotAccess().getMacroCallAssignment_7_2(), "rule__Robot__MacroCallAssignment_7_2");
			builder.put(grammarAccess.getRobotAccess().getMacroCallAssignment_7_3_1(), "rule__Robot__MacroCallAssignment_7_3_1");
			builder.put(grammarAccess.getRobotAccess().getBodyAssignment_8_1(), "rule__Robot__BodyAssignment_8_1");
			builder.put(grammarAccess.getMacroAccess().getNameAssignment_3(), "rule__Macro__NameAssignment_3");
			builder.put(grammarAccess.getMacroAccess().getParameterAssignment_4_2(), "rule__Macro__ParameterAssignment_4_2");
			builder.put(grammarAccess.getMacroAccess().getParameterAssignment_4_3_1(), "rule__Macro__ParameterAssignment_4_3_1");
			builder.put(grammarAccess.getMacroAccess().getBodyAssignment_5_1(), "rule__Macro__BodyAssignment_5_1");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_2(), "rule__Parameter__NameAssignment_2");
			builder.put(grammarAccess.getParameterAccess().getTypeAssignment_5(), "rule__Parameter__TypeAssignment_5");
			builder.put(grammarAccess.getParameterAccess().getValueAssignment_6_1(), "rule__Parameter__ValueAssignment_6_1");
			builder.put(grammarAccess.getParameterValueAccess().getValueAssignment_0(), "rule__ParameterValue__ValueAssignment_0");
			builder.put(grammarAccess.getLinkRefAccess().getRefAssignment(), "rule__LinkRef__RefAssignment");
			builder.put(grammarAccess.getParameterStringAccess().getRefAssignment_1(), "rule__ParameterString__RefAssignment_1");
			builder.put(grammarAccess.getParameterStringAccess().getValueAssignment_2(), "rule__ParameterString__ValueAssignment_2");
			builder.put(grammarAccess.getParameterPoseAccess().getRefAssignment_0(), "rule__ParameterPose__RefAssignment_0");
			builder.put(grammarAccess.getParameterPoseAccess().getValueAssignment_1(), "rule__ParameterPose__ValueAssignment_1");
			builder.put(grammarAccess.getParameterLinkAccess().getParamAssignment_0(), "rule__ParameterLink__ParamAssignment_0");
			builder.put(grammarAccess.getParameterLinkAccess().getLinkAssignment_1(), "rule__ParameterLink__LinkAssignment_1");
			builder.put(grammarAccess.getBodyAccess().getLinkAssignment_3_2(), "rule__Body__LinkAssignment_3_2");
			builder.put(grammarAccess.getBodyAccess().getLinkAssignment_3_3_1(), "rule__Body__LinkAssignment_3_3_1");
			builder.put(grammarAccess.getBodyAccess().getJointAssignment_4_2(), "rule__Body__JointAssignment_4_2");
			builder.put(grammarAccess.getBodyAccess().getJointAssignment_4_3_1(), "rule__Body__JointAssignment_4_3_1");
			builder.put(grammarAccess.getMacroCallAccess().getMacroAssignment_4(), "rule__MacroCall__MacroAssignment_4");
			builder.put(grammarAccess.getMacroCallAccess().getParameterCallAssignment_5_2(), "rule__MacroCall__ParameterCallAssignment_5_2");
			builder.put(grammarAccess.getMacroCallAccess().getParameterCallAssignment_5_3_1(), "rule__MacroCall__ParameterCallAssignment_5_3_1");
			builder.put(grammarAccess.getParameterCallAccess().getParameterAssignment_4(), "rule__ParameterCall__ParameterAssignment_4");
			builder.put(grammarAccess.getParameterCallAccess().getValueAssignment_6(), "rule__ParameterCall__ValueAssignment_6");
			builder.put(grammarAccess.getJointAccess().getNameAssignment_3(), "rule__Joint__NameAssignment_3");
			builder.put(grammarAccess.getJointAccess().getTypeAssignment_5(), "rule__Joint__TypeAssignment_5");
			builder.put(grammarAccess.getJointAccess().getParentAssignment_7(), "rule__Joint__ParentAssignment_7");
			builder.put(grammarAccess.getJointAccess().getChildAssignment_9(), "rule__Joint__ChildAssignment_9");
			builder.put(grammarAccess.getJointAccess().getOriginAssignment_10_1(), "rule__Joint__OriginAssignment_10_1");
			builder.put(grammarAccess.getJointAccess().getAxisAssignment_11_1(), "rule__Joint__AxisAssignment_11_1");
			builder.put(grammarAccess.getJointAccess().getLimitAssignment_12_1(), "rule__Joint__LimitAssignment_12_1");
			builder.put(grammarAccess.getLinkAccess().getNameAssignment_3(), "rule__Link__NameAssignment_3");
			builder.put(grammarAccess.getLinkAccess().getInertialAssignment_4_1(), "rule__Link__InertialAssignment_4_1");
			builder.put(grammarAccess.getLinkAccess().getVisualAssignment_5_1(), "rule__Link__VisualAssignment_5_1");
			builder.put(grammarAccess.getLinkAccess().getCollisionAssignment_6_1(), "rule__Link__CollisionAssignment_6_1");
			builder.put(grammarAccess.getPoseAccess().getRpyAssignment_3_1(), "rule__Pose__RpyAssignment_3_1");
			builder.put(grammarAccess.getPoseAccess().getXyzAssignment_4_1(), "rule__Pose__XyzAssignment_4_1");
			builder.put(grammarAccess.getVector3Access().getXyzAssignment_3_1(), "rule__Vector3__XyzAssignment_3_1");
			builder.put(grammarAccess.getLimitAccess().getEffortAssignment_3_1(), "rule__Limit__EffortAssignment_3_1");
			builder.put(grammarAccess.getLimitAccess().getLowerAssignment_4_1(), "rule__Limit__LowerAssignment_4_1");
			builder.put(grammarAccess.getLimitAccess().getUpperAssignment_5_1(), "rule__Limit__UpperAssignment_5_1");
			builder.put(grammarAccess.getLimitAccess().getVelocityAssignment_6_1(), "rule__Limit__VelocityAssignment_6_1");
			builder.put(grammarAccess.getInertialAccess().getOriginAssignment_3_1(), "rule__Inertial__OriginAssignment_3_1");
			builder.put(grammarAccess.getInertialAccess().getMassAssignment_4_1(), "rule__Inertial__MassAssignment_4_1");
			builder.put(grammarAccess.getInertialAccess().getInertiaAssignment_5_1(), "rule__Inertial__InertiaAssignment_5_1");
			builder.put(grammarAccess.getVisualAccess().getOriginAssignment_2_1(), "rule__Visual__OriginAssignment_2_1");
			builder.put(grammarAccess.getVisualAccess().getGeometryAssignment_4(), "rule__Visual__GeometryAssignment_4");
			builder.put(grammarAccess.getCollisionAccess().getOriginAssignment_2_1(), "rule__Collision__OriginAssignment_2_1");
			builder.put(grammarAccess.getCollisionAccess().getGeometryAssignment_4(), "rule__Collision__GeometryAssignment_4");
			builder.put(grammarAccess.getMassAccess().getValueAssignment_3_1(), "rule__Mass__ValueAssignment_3_1");
			builder.put(grammarAccess.getInertiaAccess().getIxxAssignment_3_1(), "rule__Inertia__IxxAssignment_3_1");
			builder.put(grammarAccess.getInertiaAccess().getIxyAssignment_4_1(), "rule__Inertia__IxyAssignment_4_1");
			builder.put(grammarAccess.getInertiaAccess().getIxzAssignment_5_1(), "rule__Inertia__IxzAssignment_5_1");
			builder.put(grammarAccess.getInertiaAccess().getIyyAssignment_6_1(), "rule__Inertia__IyyAssignment_6_1");
			builder.put(grammarAccess.getInertiaAccess().getIyzAssignment_7_1(), "rule__Inertia__IyzAssignment_7_1");
			builder.put(grammarAccess.getInertiaAccess().getIzzAssignment_8_1(), "rule__Inertia__IzzAssignment_8_1");
			builder.put(grammarAccess.getGeometryAccess().getBoxAssignment_3_1(), "rule__Geometry__BoxAssignment_3_1");
			builder.put(grammarAccess.getGeometryAccess().getCylinderAssignment_4_1(), "rule__Geometry__CylinderAssignment_4_1");
			builder.put(grammarAccess.getGeometryAccess().getSphereAssignment_5_1(), "rule__Geometry__SphereAssignment_5_1");
			builder.put(grammarAccess.getGeometryAccess().getMeshAssignment_6_1(), "rule__Geometry__MeshAssignment_6_1");
			builder.put(grammarAccess.getBoxAccess().getSizeAssignment_3_1(), "rule__Box__SizeAssignment_3_1");
			builder.put(grammarAccess.getCylinderAccess().getLengthAssignment_3(), "rule__Cylinder__LengthAssignment_3");
			builder.put(grammarAccess.getCylinderAccess().getRadiusAssignment_5(), "rule__Cylinder__RadiusAssignment_5");
			builder.put(grammarAccess.getSphereAccess().getRadiusAssignment_3(), "rule__Sphere__RadiusAssignment_3");
			builder.put(grammarAccess.getMeshAccess().getFilenameAssignment_3(), "rule__Mesh__FilenameAssignment_3");
			builder.put(grammarAccess.getMeshAccess().getScaleAssignment_4_1(), "rule__Mesh__ScaleAssignment_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private XacroGrammarAccess grammarAccess;

	@Override
	protected InternalXacroParser createParser() {
		InternalXacroParser result = new InternalXacroParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public XacroGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XacroGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
