/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.kinematics.parser.antlr;

import com.google.inject.Inject;
import de.fraunhofer.ipa.kinematics.parser.antlr.internal.InternalKinematicsParser;
import de.fraunhofer.ipa.kinematics.services.KinematicsGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class KinematicsParser extends AbstractAntlrParser {

	@Inject
	private KinematicsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalKinematicsParser createParser(XtextTokenStream stream) {
		return new InternalKinematicsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Robot";
	}

	public KinematicsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KinematicsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
