<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kinematics" nsURI="http://www.example.org/kinematics" nsPrefix="kinematics">
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Visual" eType="#//Geometry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Collision" eType="#//Geometry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Joint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parent" eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Child" lowerBound="1" upperBound="-1"
        eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Prefix" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Origin" lowerBound="1"
        eType="#//Transform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Axis" lowerBound="1" eType="#//Vector3d"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Geometry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Mesh" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Translation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="r" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="p" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transform">
    <eStructuralFeatures xsi:type="ecore:EReference" name="XYZ" lowerBound="1" eType="#//Translation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RPY" lowerBound="1" eType="#//Rotation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vector3d">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="X" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Z" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
</ecore:EPackage>
