/*
 * generated by Xtext 2.25.0
 */
package de.fraunhofer.ipa.kinematics.ide;


/**
 * Use this class to register ide components.
 */
public class KinematicsIdeModule extends AbstractKinematicsIdeModule {
}
